# "service" is the name of this project. This will also be added to your AWS resource names.
service: line-obsidian-webhook

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1

  environment:
    GIT_REPO: https://github.com/YuugouOhno/obsidian-vault.git
    GH_TOKEN: ${env:GH_TOKEN}
    CHANNEL_SECRET: ${env:CHANNEL_SECRET}
    TZ: Asia/Tokyo

functions:
  webhook:
    handler: src/handler.main
    memorySize: 512
    timeout: 30
    url: true                   # Lambda Function URL (HTTP API)
    layers:
      - arn:aws:lambda:ap-northeast-1:553035198032:layer:git-lambda2:8
    events:
      - httpApi:
          path: /webhook
          method: post